calc/urls.py
from django.urls import path
from calc import views

app_name = 'calc'

urlpatterns = [
    # 입 출력
    path('input/', views.input, name='input'),
    path('output/', views.output, name='output'),

    # 홀수/짝수 판별
    path('input_num/', views.input_num, name='input_num'),
    path('even_odd/', views.even_odd, name='even_odd'),

    # 구구단 계산
    path('input_dan/', views.input_dan, name='input_dan'),
    path('gugudan/', views.gugudan, name='gugudan')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from poll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 127.0.0.1:8000/poll
    path('poll/', include('poll.urls')),
    # 127.0.0.1:8000/
    path("", views.index),

    # 127.0.0.1:8000/calc
    path("calc/", include('calc.urls'))
]

poll/urls.py
from django.urls import path
from . import views

app_name = 'poll'

urlpatterns = [
    # /poll/
    path("", views.index, name='index'),
    # /poll/2
    path("<int:question_id>/", views.detail, name='detail'),
    # /poll/2/vote
    path("<int:question_id>/vote/", views.vote, name='vote'),

    path("<int:question_id>/results/", views.results, name='results'),


    # /poll/val_jq
    path("val_jq/", views.val_jq, name='val_jq'),
    path("parent_jq/", views.parent_jq, name='parent_jq'),
    path("submenu/", views.submenu, name="submenu"),
]

calc/models.py
from django.db import models

# Create your models here.

poll/models.py
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

calc/views.py
from django.http import HttpResponse
from django.shortcuts import render

def input(request): # HttpRequest
    #return HttpResponse("입력 화면 입니다.")
    return render(request, 'calc/input.html')

def output(request):
    # 데이터 받아서 넘기기
    name = request.POST['name']
    age = int(request.POST['age'])

    context = {'name': name, 'age': age}
    return render(request, 'calc/output.html', context)

def input_num(request):
    return render(request, 'calc/input_num.html')

def even_odd(request):
    # 숫자 받아오기
    num = int(request.POST['num'])

    # 홀수/짝수 계산
    if num % 2 == 1:
        context = {'num': num, 'result' : "홀수입니다."}
    else:
        context = {'num': num, 'result' : "짝수입니다."}

    return render(request, 'calc/even_odd.html', context)

def input_dan(request):
    return render(request, 'calc/input_dan.html')


def gugudan(request):
    # dan 전송받기
    dan = int(request.POST['dan'])

    # 구구단 계산하기
    times = []   # dan = 4, times=[4, 8, 12...32, 36]
    for i in range(1, 10):
        times.append(dan * i)

    context = {'dan': dan, 'times': times}
    return render(request, 'calc/gugudan.html', context)

poll/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question
from django.urls import reverse

def index(request):
    question_list = Question.objects.order_by('-pub_date')
    context = {'question_list': question_list}
    return render(request, 'poll/list.html', context)

def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'poll/detail.html', context)

def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except KeyError:

        return render(request, 'poll/detail.html', {
            'question': question,
            'error_message': '선택을 해주세요!'
        })
    else:
        selected_choice.votes += 1    #선택 하면 1이 증가함
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll:results', args=(question.id,)))

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'poll/results.html', context)

def val_jq(request):
    return render(request, 'poll/val_jq.html')

def parent_jq(request):
    return render(request, 'poll/parent_jq.html')

def submenu(request):
    return render(request, 'poll/submenu.html')

templates/calc/even_odd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>홀수/짝수 판정</title>
</head>
<body>
  <h2>홀수/짝수 판정</h2>
  <h3>입력받은 숫자는 {{ num }}</h3>
  <h3>결과는 {{ result }}</h3>

</body>
</html>

templates/calc/gugudan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>구구단 출력</title>
</head>
<body>
  <h2>{{ dan }} 단</h2>
  {% for val in times %}
    {{ dan }} x {{ forloop.counter }} = {{ val }}<br>
  {% endfor %}
</body>
</html>

templates/calc/input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>입력 화면</title>
</head>
<body>
  <form action="{% url 'calc:output' %}" method="post">
      {% csrf_token %}
    <p>
      <label for="name">이름 : </label>
      <input type="text" name="name" id="name">
    </p>
      <p>
      <label for="age">나이 : </label>
      <input type="text" name="age" id="age">
    </p>
    <input type="submit" value="전송">
  </form>
</body>
</html>

templates/calc/input_dan.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>숫자 입력 화면</title>
</head>
<body>
  <form action="{% url 'calc:gugudan' %}" method="post">
    {% csrf_token %}
    <p>
      <label>단 입력: </label>
      <input type="text", name="dan">
    </p>
    <button type="submit">확인</button>
  </form>
</body>
</html>

templates/calc/input_num.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>숫자 입력 화면</title>
</head>
<body>
  <form action="{% url 'calc:even_odd' %}" method="post">
    {% csrf_token %}
    <p>
      <label>숫자: </label>
      <input type="text", name="num">
    </p>
    <button type="submit">확인</button>
  </form>
</body>
</html>

templates/calc/output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>출력 화면</title>
</head>
<body>
  <h3>이름 : {{ name }}</h3>
  <h3>나이 : {{ age }}</h3>
</body>
</html>

templates/poll/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'poll/bootstrap.css' %}">
    <title>투표 하기</title>
</head>
<body>
  <div class="jumbotron">
        <div class="text-center">
            <h1>투표 하기</h1>
        </div>
  </div>
  <div class="container">
      <form action="{% url 'poll:vote' question.id %}" method="post">
        {% csrf_token %}
        <h3>{{ question.question_text }}</h3>
        <!-- 선택을 하지 않고 투표 버튼을 누른 경우 에러 처리-->
        {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}"
               value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}" style="line-height: 2rem">
          {{ choice.choice_text }}
        </label>
        <br>
        {% endfor %}
        <p><input type="submit" value="투표"></p>
      </form>
    </div>
</body>
</html>

templates/poll/list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'poll/bootstrap.css' %}">
    <title>설문지 목록</title>
</head>
<body>
    <div class="jumbotron">
        <div class="text-center">
            <h1>설문지 목록</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% if question_list %}
                {% for question in question_list %}
                <div class="col-4">
                    <a href="{% url 'poll:detail' question.id %}">
                        <h4 style="line-height: 2.5rem">
                            {{ forloop.counter }}. {{ question.question_text }}
                        </h4>
                    </a>
                </div>
                {% endfor %}
            {% else %}
                <p>설문이 없습니다.</p>
            {% endif %}
        </div>
    </div>
</body>
</html>

templates/poll/parent_jq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>parent() 예제</title>
    <style>
        .wrap *{
            display: block;
            border: 2px solid gray;
            color: gray;
            padding: 10px;
            margin: 20px;
        }
    </style>
</head>
<body>
    <div class="wrap">
        <ul>ul (grandparent)
            <li>li(direct parent)
                <span>span</span>
            </li>
        </ul>
    </div>

    <script>
        $(document).ready(function(){
            $("span").parent().css({
                "color": "blue", "border": "2px solid red"});
        });
    </script>
</body>
</html>

templates/poll/results.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'poll/bootstrap.css' %}">
    <title>투표 결과</title>
</head>
<body>
  <div class="jumbotron">
        <div class="text-center">
            <h1>투표 결과</h1>
        </div>
  </div>
  <div class="container">
    <h3>{{ question.question_text }}</h3>
    <ul>
      {% for choice in question.choice_set.all %}
      <li class="my-3">
        {{ choice.choice_text }} - {{ choice.votes }}votes
      </li>
      {% endfor %}
    </ul>
    <a href="{% url 'poll:detail' question.id %}" >다시 투표하시겠습니까?</a>
  </div>
</body>
</html>

templates/poll/submenu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <title>학교 사이트 메뉴</title>
    <style>
        .wrap a{text-decoration: none; color: #222}
    </style>
</head>
<body>
    <div class="wrap">
        <p class="btn1">
            <a href="#">학교안내</a>
        </p>
        <ul class="ul1" style="display: none">
            <li>학교장인사말</li>
            <li>학교연혁</li>
            <li>찾아오시는길</li>
        </ul>
        <p class="btn2">
            <a href="#">학교생활</a>
        </p>
        <ul class="ul2" style="display: none">
            <li>공지사항</li>
            <li>가정통신문</li>
            <li>동아리활동</li>
        </ul>
    </div>

    <script>
        $(document).ready(function(){
            //마우스를 올려놓았을때 이벤트
            $(".btn1 a").on('mouseover', function(){
                var y = $(this);
                y.parent().next().show();  //parent():P태그 next():형제(ul)
                y.css("background", "lightgreen");
            });
            $(".btn1 a").on('mouseout', function(){
                var y = $(this);
                y.parent().next().hide();
                y.css("background", "white");
            });

            // 마우스 클릭시 이벤트
            $(".btn2 a").on('click', function(){
                $(".ul2").css({'display': 'block'});
            });
        });
    </script>
</body>
</html>

templates/poll/val_jq.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <script src="{% static 'poll/jquery-3.6.0.js' %}"></script>
    <title>val()함수 예제</title>
</head>
<body>
    <input type="text" id="t_input">
    <button>입력</button>
    <p>결과 <input type="text" id="t_output" disabled></p>

    <script>
        $(document).ready(function(){
            $("button").on('click', function(){
                var text = $("#t_input").val();
                $("#t_output").val(text)
            });
        });
    </script>
</body>
</html>